// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTvm9ptRd99sCy0bmojXVPDmw9VAhbUw',
    appId: '1:1030346125092:web:a06db1ed1088325986cdb1',
    messagingSenderId: '1030346125092',
    projectId: 'garageezway',
    authDomain: 'garageezway.firebaseapp.com',
    databaseURL: 'https://garageezway-default-rtdb.firebaseio.com',
    storageBucket: 'garageezway.firebasestorage.app',
    measurementId: 'G-FWXS9XGV9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpI7T2WN21JYDOuJxLZHalEvHbCIHmhpk',
    appId: '1:1030346125092:android:becc0354c489b90486cdb1',
    messagingSenderId: '1030346125092',
    projectId: 'garageezway',
    databaseURL: 'https://garageezway-default-rtdb.firebaseio.com',
    storageBucket: 'garageezway.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7wYQu4DGzWTVg572XBXjUeaFPMPuMGsc',
    appId: '1:1030346125092:ios:8957f756afd7d52986cdb1',
    messagingSenderId: '1030346125092',
    projectId: 'garageezway',
    databaseURL: 'https://garageezway-default-rtdb.firebaseio.com',
    storageBucket: 'garageezway.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7wYQu4DGzWTVg572XBXjUeaFPMPuMGsc',
    appId: '1:1030346125092:ios:8957f756afd7d52986cdb1',
    messagingSenderId: '1030346125092',
    projectId: 'garageezway',
    databaseURL: 'https://garageezway-default-rtdb.firebaseio.com',
    storageBucket: 'garageezway.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTvm9ptRd99sCy0bmojXVPDmw9VAhbUw',
    appId: '1:1030346125092:web:9b175f497f2935d786cdb1',
    messagingSenderId: '1030346125092',
    projectId: 'garageezway',
    authDomain: 'garageezway.firebaseapp.com',
    databaseURL: 'https://garageezway-default-rtdb.firebaseio.com',
    storageBucket: 'garageezway.firebasestorage.app',
    measurementId: 'G-W7YMQMLSBC',
  );

}